#!/usr/bin/ruby

BEGIN {
    require 'logger'
    require 'octokit'
    require 'colorize'
    require 'json'

    puts "Initializing Anafora pull request reports..."
    t = Time.new

    # Set org name.
    $ORG = "stolostron"

    # User GitHub token.
    $GITHUB_TOKEN = ENV["GITHUB_TOKEN"]
    $GITHUB_URL = "https://github.com"

    $ANAFORA_URL = "#{$GITHUB_URL}/#{$ORG}/anafora"

    # Slack token and webhook url.
    $SLACK_BOT_TOKEN = ENV["SLACK_BOT_TOKEN"]
    $SLACK_CHANNEL_ID = ENV["SLACK_CHANNEL_ID"]
    $SLACK_WEBHOOK_URL = ENV["SLACK_WEBHOOK_URL"]

    # Local report directory.
    $REPORT_DIR = "report/#{t.strftime("%m-%d-%y")}"
    $REPORT_FILE = "#{$REPORT_DIR}/pr-report-#{t.strftime("%s")}"

    $REPOSITORIES_FILE_PATH = ENV["REPOSITORIES_FILE_PATH"] ? ENV["REPOSITORIES_FILE_PATH"] : "REPOSITORIES.txt"

    unless Dir.exist?($REPORT_DIR)
        puts "#{$REPORT_DIR} does not exist. Creating report directory."
        Dir.mkdir($REPORT_DIR)
    else
        puts "#{$REPORT_DIR} already exists. Skipping creating new report directory."
    end

    $logger = Logger.new File.new("#{$REPORT_FILE}.log", "w+")

    # Check to see if the GITHUB_TOKEN and SLACK_WEBHOOK_URL exist and are configured correctly.
    unless ($GITHUB_TOKEN && $SLACK_WEBHOOK_URL)
        err = "GITHUB_TOKEN and SLACK_WEBHOOK_URL are required to be configured. Please ensure that the GITHUB_TOKEN and SLACK_WEBHOOK_URL are configured correctly."
        $logger.error err
        abort err
    else
        $logger.info "Detected GITHUB_TOKEN and SLACK_WEBHOOK_URL. Preparing to find #{$REPOSITORIES_FILE_PATH}."
    end

    # Check to see if the repository list is available. This is required to check if the repository contains pull requests.
    unless File.exist?($REPOSITORIES_FILE_PATH)
        err = "Repositories file #{$REPOSITORIES_FILE_PATH} does not exist. Please create it and try again." 
        $logger.error err
        abort err
    else
        $logger.info "Found #{$REPOSITORIES_FILE_PATH}."
    end

    client = Octokit::Client.new(:access_token => $GITHUB_TOKEN)
    $total_pr_count = 0
}

END {
    message = "Total number of pull requests received: #{$total_pr_count}"
    $logger.info message
    puts "\n#{message}"

    send_report_to_slack(webhook: $SLACK_WEBHOOK_URL, body: File.read("#{$REPORT_FILE}.txt"))
}

def send_report_to_slack (**args)
    status = $total_pr_count >= 10 ? 'warning' : 'good'
    payload = {
        :attachments => [
            { 
                "color" => status,
                "text" => args[:body],
                "title" => "View Pull Request Report in Github -> Anafora",
                "title_link" => $ANAFORA_URL
            }
        ],
        :text => ":announcement: Hello team! Here is your weekly `GitHub Pull Requests Report`!\n\n" \
            ":#{status}:There are #{$total_pr_count} active pull requests opened! Please remember to review or close any inactive pull request.\n\n"
    }.to_json

    # Post the report to the configured slack channel.
    res = `curl -s -X POST --data-urlencode 'payload=#{payload}' #{args[:webhook]}`
    err = "Failed to post the report to the slack channel."
    
    unless res == "ok"
        $logger.error err
        abort err
    end

    # Get the timestamp of the message that was posted.
    res = `curl -s -H "Authorization: Bearer #{$SLACK_BOT_TOKEN}" -d "channel=#{$SLACK_CHANNEL_ID}" -d "limit=1" https://slack.com/api/conversations.history`
    data = JSON.parse(res, object_class: OpenStruct)
    ts = data.messages[0].ts

    unless !ts.nil?
        err = "Failed to message that was posted timestamp within the slack channel."
        $logger.error err
    else
        # Optional: Add thread reaction to the message that we posted.
        res = `curl -s -H "Authorization: Bearer #{$SLACK_BOT_TOKEN}" -d "channel=#{$SLACK_CHANNEL_ID}" -d "timestamp=#{ts}" -d "name=usethreads" https://slack.com/api/reactions.add`
    end

    $logger.close()

    # Create a thread and add the log file that was captured during the runtime.
    resp = `curl -H 'Authorization: Bearer #{$SLACK_BOT_TOKEN}' -F 'file=@#{$REPORT_FILE}.log' -F 'initial_comment=Log data generated by the report' -F 'filetype=text' -F 'channels=#{$SLACK_CHANNEL_ID}' -F 'thread_ts=#{ts}' https://slack.com/api/files.upload`
end

# Open the text file that will be sent to the slack webhook.
f = File.open("#{$REPORT_FILE}.txt", 'w+')

File.readlines($REPOSITORIES_FILE_PATH).each do |repository|
    r = client.pull_requests("#{$ORG}/#{repository.strip}", :state => 'open')

    puts "\nChecking #{$ORG}/#{repository.strip} for open pull request.\n"

    message = "#{$ORG}/#{repository.strip} contains: #{r.count} pull requests."
    $logger.info message

    unless r.count == 0
        message = "Current active <#{$GITHUB_URL}/#{$ORG}/#{repository.strip}/pulls|PRs> in `#{$ORG}/#{repository.strip}`\n"
        f.puts message
    end

    unless !r.empty?
        puts "\t• No pull requests were found within the #{$ORG}/#{repository.strip} repository.".yellow
    else
        r.each do |pr|
            message = "Received pull request: (#{pr.number}) #{pr.title}."
            $logger.info message
            puts "\t• #{message}".green

            message = "\t• <#{pr.html_url}|#{pr.number}> - #{pr.title} <@#{pr.user.login}>"
            f.puts message
        end
        f.puts("\n")
    end

    $total_pr_count += r.count
end

f.close()
